import click
import os
from .run_agent import main as run_agent_main

@click.group()
def cli():
    """A CLI for the LinkedIn Scraper Agent."""
    pass

@cli.command()
def configure():
    """Interactively configure the .env file with your credentials."""
    click.echo("--- LinkedIn Agent Configuration ---")
    click.echo("This will create a .env file to store your credentials.")
    
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    env_path = os.path.join(project_root, '.env')

    if os.path.exists(env_path):
        if not click.confirm(f"\nWarning: .env file already exists at {env_path}.\nDo you want to overwrite it?"):
            click.echo("Configuration cancelled.")
            return

    # --- Gather Information ---
    linkedin_user = click.prompt("Enter your LinkedIn email", type=str)
    linkedin_pass = click.prompt("Enter your LinkedIn password", hide_input=True, confirmation_prompt=True)
    db_host = click.prompt("Enter your Database Host", default="localhost")
    db_user = click.prompt("Enter your Database User", default=os.getlogin())
    db_name = click.prompt("Enter your Database Name", default=os.getlogin())

    # --- Create .env content ---
    env_content = f"""# .env - Environment variables for the LinkedIn Agent
# This file is generated by 'linkedin-agent configure' and should NOT be committed to git.

# LinkedIn Credentials
LINKEDIN_USERNAME="{linkedin_user}"
LINKEDIN_PASSWORD="{linkedin_pass}"

# Database Configuration
DB_HOST={db_host}
DB_USER={db_user}
DB_NAME={db_name}
"""

    # --- Write to file ---
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        click.secho(f"\nSuccessfully created .env file at: {env_path}", fg="green")
        click.echo("You are now ready to run the agent with 'linkedin-agent run'.")
    except Exception as e:
        click.secho(f"Error: Could not write to {env_path}. Reason: {e}", fg="red")


@cli.command()
@click.argument('job_name', default='linkedin_recruiter_search')
def run(job_name):
    """Runs the LinkedIn agent for a specific job."""
    click.echo(f"INFO: Starting agent for job: {job_name}")
    try:
        run_agent_main(job_name)
        click.echo(f"INFO: Agent finished job: {job_name}")
    except Exception as e:
        click.echo(f"ERROR: An error occurred during agent execution: {e}", err=True)

if __name__ == '__main__':
    cli()
